### ISSUE TITLE
Humanize duration object

### ISSUE THREAD

**Issue by nstanard** [icholy/Duration.js#13]
I'd like to propose the functionality of converting the duration object back into the readable string.

For instance:
`var d = new Duration("6w5d4h3m2s1ms");`
`d.humanizeDuration(format);`

humanizeDuration = function that takes a format string value.
format = a string to specify the output format. E.g. "wdh" or "dh"

"wdh" returns `"6w5d4h"`
"dh" return `"47d4h"`

I will be taking a stab at adding this feature and opening a PR but wanted to run this by an issue to get feedback first. If you have any concerns with this functionality I'd love to talk about that before I really dig in.

**Comment by icholy** [comment]
Instead of adding an additional method, `toString()` should take an optional `format` parameter which defaults to a format that maintains the current behaviour. 

There's a problem though: `ms`. Is that `minute` `second` or `millisecond`? The format you're describing is ambiguous.

**Comment by nstanard** [comment]
> Instead of adding an additional method, toString() should take an optional format parameter which defaults to a format that maintains the current behaviour.

**Comment by nstanard** [comment]
> There's a problem, though: ms. Is that minute second or millisecond? The format you're describing is ambiguous.

Great point. Thank you for responding so quickly.

**Comment by icholy** [comment]
I don't like the case sensitive format either. I was thinking comma separated `w,d,h,m,s,ms`, but that's ugly too. There could be fully fledged formatting: `{w} week(s) {d} day(s) {s} second(s)`. But that would require implementing a templating language (I'm not willing to pull in a dependency). However, this seems like too much and beyond the scope of this project.

**Comment by nstanard** [comment]
> However, this seems like too much and beyond the scope of this project.

I understand if you feel that way. I've already converted it where I needed it but thought it would come in really handy. I'm using this module to convert only for display purposes. So being able to pass a format and get that back from the object would simply save me the logic of getting the remainder and formatting it myself. 

This is not a huge priority for me right now though either. If I can come up with a format that I think you'll like I'll open a PR.

**Comment by StefanBrand** [comment]
There is a widespread date format language called [strftime](http://strftime.net/). It is used by Liquid, for example.

**Comment by icholy** [comment]
@StefanBrand how does that work with duration formatting though?
