### ISSUE TITLE
milliseconds as the smallest unit

### ISSUE THREAD

**Issue by icholy** [icholy/Duration.js#3]
In the current implementation, nanoseconds are the smallest unit. This was done so it would be easy to work with Go's `time.Duration` type. 

Javascript's `Date` uses milliseconds as the smallest unit. So we can write code like this.

``` js
var now   = new Date(),
    tenM  = Duration.parse("10m"),
    later = new Date(now + tenM.milliseconds());

var epoch = Date.parse("Janulary 1, 1970"),
    now   = new Date(),
    diff  = new Duration((now - epoch) * Duration.millisecond);
```

If milliseconds were the smallest unit then we could write.

``` js
var now   = new Date(),
    tenM  = Duration.parse("10m"),
    later = new Date(now + tenM);

var epoch = Date.parse("Janulary 1, 1970"),
    now   = new Date(),
    diff  = new Duration(now - epoch);
```

It's a trade-off between being easy to use with `Date` or Go's `time.Duration`.

**Comment by vinnitu** [comment]
if milliseconds is default why it is error

```js
const { Duration } = require('@icholy/duration');

new Duration('1000'); // == 1000ms
```

```
node_modules/@icholy/duration/dist/duration.js:144
            throw new Error("invalid duration");
            ^

Error: invalid duration
```

**Comment by icholy** [comment]
@vinnitu you're missing the unit in the string. `new Duration('1000ms');`. If you want to pass the number of milliseconds, pass it as a number: `new Duration(1000);`

**Comment by vinnitu** [comment]
I see but in my case I get params from querystring where all params is string type. Now I use

```js
const { Duration } = require('@icholy/duration');
const toDuration = (s) => isNaN(+s) ? +new Duration(s) : +s;
```

**Comment by icholy** [comment]
Coerce the string to a number like you do in the other cases.

``` js
const { Duration } = require('@icholy/duration');
const toDuration = s => isNaN(+s) ? +new Duration(+s) : +s;
```

**Comment by vinnitu** [comment]
https://github.com/icholy/Duration.js/issues/3#issuecomment-758540472

**Comment by icholy** [comment]
`'1000'` is not a valid duration string. That is by design. Adjust your code to take that into account.

**Comment by vinnitu** [comment]
```js
// GET http://example.com/test?duration=1000
app.get('/test', (req, res) => toDuration(req.query.duration)) // req.query.duration always of String type in this casual case
```
